---
- hosts: "{{ hostlist }}"
  become: yes
  become_user: root
  vars:
    ansible_ssh_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"

  roles:
    - role: dev-sec.os-hardening
      vars:
        sysctl_overwrite:
          # Enable IPv4 traffic forwarding.
          net.ipv4.ip_forward: 1

    - role: oefenweb.fail2ban
      vars:
        fail2ban_destemail: "{{ email }}"
        fail2ban_bantime: -1
        fail2ban_services:
          - name: sshd
      when: install_fail2ban

    - role: rkhunter-ansible-role
      vars:
        rkhunter_report_mail_address: "{{ email }}"
        rkhunter_diag_scan: yes
        rkhunter_allow_ssh_root_login: yes
      when: install_rkhunter

    - role: robertdebock.logwatch
      vars:
        logwatch_mailto: "{{ email }}"
      when: install_logwatch

    - role: maxlareo.portsentry
      when: install_portsentry

  tasks:
    - include: tasks/cron_update.yml
      when: install_automatic_update
